# Generated by Django 4.2.7 on 2023-11-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptanimelistweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='imgs/')),
                ('detail', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
